name: myapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  fpdart: ^1.1.0
  supabase_flutter: ^2.5.7
  flutter_bloc: ^8.1.6
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  equatable: ^2.0.5
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  iconsax: ^0.0.8
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.7.0
  location: ^5.0.0
  flutter_polyline_points: ^2.1.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2
  build_runner: ^2.4.11

  
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/login_register_pages/
    - assets/images/places/
    - assets/images/cover/
    - assets/images/profil/
    - assets/lotties/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
       - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
       - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
         weight: 500
       - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
         weight: 700
        
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
